### ISSUE TITLE
Trouble with size

### ISSUE THREAD

**Issue by georgiev-anton** [SeregPie/VueChart#1]
Hi. 
I have 3 charts in my bootstrap table. 
They are drawn on each other. Why?(

```
<div class="container" id="head"> 
 <div class="row pt-5">
        <div class="col chart-container">
            <h2>Оперативная память</h2>
            <vue-chart id="memoryChart"
                       v-bind:type="charts.memChartConfig.type"
                       v-bind:data="charts.memChartConfig.data"
                       v-bind:options="charts.memChartConfig.options"
                       v-bind:update-config="charts.memChartConfig.updateConfig"
            >
            </vue-chart>    
        </div>
    </div>
    <div class="row pt-5">
        <div class="col mt-5 chart-container">
            <h2>Загрузка процессора</h2>
            <vue-chart id="cpuChart"
                       v-bind:type="charts.cpuChartConfig.type"
                       v-bind:data="charts.cpuChartConfig.data"
                       v-bind:options="charts.cpuChartConfig.options"
                       v-bind:update-config="charts.cpuChartConfig.updateConfig"
            >
            </vue-chart>
        </div>
    </div>
    <div class="row pt-5">
        <div class="col mt-5 chart-container">
            <h2>Температура процессора</h2>
            <vue-chart id="cpuTempChart"
                       v-bind:type="charts.cpuTempChartConfig.type"
                       v-bind:data="charts.cpuTempChartConfig.data"
                       v-bind:options="charts.cpuTempChartConfig.options"
                       v-bind:update-config="charts.cpuTempChartConfig.updateConfig"
            >
            </vue-chart>
        </div>
    </div>
</div>
```

![screenshot_2019-01-14_16-11-14](https://user-images.githubusercontent.com/16887654/51109443-0e047b80-1817-11e9-8124-785ecbf96ee5.png)

**Comment by SeregPie** [comment]
Hi.
Try setting the height for each component. Maybe this is the problem.

```
<vue-chart 
  style="height: 200px;"
  ...
></vue-chart>
```

**Comment by georgiev-anton** [comment]
I cannot use this style, because I create a table and I need the column to be aligned with the graph itself.
I use style height: auto; in my column, but it is created 47px

**Comment by SeregPie** [comment]
A codepen or similar would be helpful. Can you upload your code as an working example somewhere?

Per default chart container has its width and height set to 100%

**Comment by georgiev-anton** [comment]
Yes, thanks ) I need to fix only the table
https://pastebin.com/1AU8CPPG

**Comment by SeregPie** [comment]
Sorry. This is not enough. This is not a working example. It's only html.
Try to make a working example here:
https://codepen.io/pen/

**Comment by georgiev-anton** [comment]
Sorry, im forget JS.
https://codepen.io/anon/pen/YdBBaq
this work draw charts, but dont get data. 
I hope this helps fix the markup.
thanks)

**Comment by SeregPie** [comment]
You need to set `maintainAspectRatio: false` in the options and `style="height: <your_value>px;"` in the html.

https://codepen.io/SeregPie/pen/WLPWvb

**Comment by georgiev-anton** [comment]
I need the height to change dynamically depending on the size of the window.
I decided this: put the listener to resize the window and change the height of the column depending on the size of the chart
thanks for the help
