### ISSUE TITLE
Chart update

### ISSUE THREAD

**Issue by madmax17** [SeregPie/VueChart#2]
How can I update the chart after changing the data?

**Comment by SeregPie** [comment]
It updates automatically if the data changes. If you want to change the data directly, use `Vue.set` and `Vue.delete` functions.
https://vuejs.org/v2/guide/reactivity.html

**Comment by madmax17** [comment]
Yeah the data updated fine but I couldn't get the **labels** to update.

After hours of trying it seems vue js didn't update the labels not even with vue Set, the fix is rather strange.

setTimeout(() => {
                    this.chartData.labels = ['Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
 }, 0);

**Comment by SeregPie** [comment]
Just tested it. Look. Minimal example.
https://codepen.io/SeregPie/pen/KKPEqvX

**Comment by madmax17** [comment]
Yeah it works, I had a mistake.

Thank you.
