### ISSUE TITLE
VueChart not defined

### ISSUE THREAD

**Issue by DaveInTO** [SeregPie/VueChart#4]
Recently something broke.
VueChart not defined. 
Using Vue2 - UMD modules for chart.js.

**Comment by SeregPie** [comment]
Did you install `chart.js` as peer dependency?

**Comment by DaveInTO** [comment]
<script src="https://unpkg.com/chart.js"></script>
<script src="https://unpkg.com/@seregpie/vue-chart"></script>
Yes.
So removed
 components: {
                        "vue-chart": VueChart
                },

And it got rid of the error and the page is rendering now(without any charts)

Uncaught TypeError t is undefined due-chart:1

**Comment by SeregPie** [comment]
The chart now works with Vue 2 and 3. So you need `vue-demi`. Look inside readme.

For Vue 2.

```html
<script src="https://unpkg.com/vue@2"></script>
<script src="https://unpkg.com/@vue/composition-api"></script>
<script src="https://unpkg.com/vue-demi"></script>
<script src="https://unpkg.com/chart.js@3"></script>
<script src="https://unpkg.com/@seregpie/vue-chart"></script>
```

For Vue 3.

```html
<script src="https://unpkg.com/vue@3"></script>
<script src="https://unpkg.com/vue-demi"></script>
<script src="https://unpkg.com/chart.js@3"></script>
<script src="https://unpkg.com/@seregpie/vue-chart"></script>
```

**Comment by DaveInTO** [comment]
Yup..vue-demi was the trick, thanks, just missing from the Vue 2 docs in the README.

Have a great day!
